openapi: 3.0.0
info:
  title: Simulation API
  description: API for managing robotics simulation environments
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Development server

paths:
  /simulation/run:
    post:
      summary: Start a new simulation session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationRequest'
      responses:
        '201':
          description: Simulation session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationSession'
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /simulation/{session_id}:
    get:
      summary: Get simulation session status
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: Simulation session ID
      responses:
        '200':
          description: Simulation session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationSession'
        '404':
          description: Simulation session not found
        '500':
          description: Internal server error
    delete:
      summary: Stop/terminate a simulation session
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: Simulation session ID
      responses:
        '200':
          description: Simulation terminated successfully
        '404':
          description: Simulation session not found
        '500':
          description: Internal server error

  /simulation/{session_id}/logs:
    get:
      summary: Get simulation logs
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: Simulation session ID
      responses:
        '200':
          description: Simulation logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationLogs'
        '404':
          description: Simulation session not found
        '500':
          description: Internal server error

  /simulation/environments:
    get:
      summary: List available simulation environments
      responses:
        '200':
          description: List of available simulation environments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SimulationEnvironment'

components:
  schemas:
    SimulationRequest:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          description: User ID initiating the simulation
        chapter_id:
          type: string
          format: uuid
          description: Chapter context for the simulation
        tutorial_id:
          type: string
          format: uuid
          description: Tutorial ID for the simulation
        environment:
          type: string
          enum: [gazebo, isaac, unity]
          description: Target simulation environment
        parameters:
          type: object
          description: Simulation-specific parameters
        hardware_target:
          type: string
          enum: [jetson, rtx, simulation-only]
          description: Target hardware platform
      required:
        - user_id
        - environment

    SimulationSession:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        chapter_id:
          type: string
          format: uuid
        tutorial_id:
          type: string
          format: uuid
        environment:
          type: string
          enum: [gazebo, isaac, unity]
        status:
          type: string
          enum: [running, completed, failed, terminated]
        parameters:
          type: object
        created_at:
          type: string
          format: date-time
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        logs_url:
          type: string
          description: URL to access simulation logs

    SimulationLogs:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        logs:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
              level:
                type: string
                enum: [info, warning, error, debug]
              message:
                type: string
              source:
                type: string
                description: Component that generated the log
        summary:
          type: object
          description: Summary of the simulation execution

    SimulationEnvironment:
      type: object
      properties:
        name:
          type: string
          enum: [gazebo, isaac, unity]
        version:
          type: string
        capabilities:
          type: array
          items:
            type: string
        supported_hardware:
          type: array
          items:
            type: string
            enum: [jetson, rtx, simulation-only]
        status:
          type: string
          enum: [available, unavailable, maintenance]